/* SPDX-License-Identifier: GPL-2.0+ */

#ifndef __AX45MP_SBI_H
#define __AX45MP_SBI_H

#define SBI_EXT_ANDES		0x0900031E

enum ax45mp_sbi_ext_fid {
	AX45MP_SBI_EXT_GET_MCACHE_CTL_STATUS = 0,
	AX45MP_SBI_EXT_GET_MMISC_CTL_STATUS,
	AX45MP_SBI_EXT_SET_MCACHE_CTL,
	AX45MP_SBI_EXT_SET_MMISC_CTL,
	AX45MP_SBI_EXT_ICACHE_OP,
	AX45MP_SBI_EXT_DCACHE_OP,
	AX45MP_SBI_EXT_L1CACHE_I_PREFETCH,
	AX45MP_SBI_EXT_L1CACHE_D_PREFETCH,
	AX45MP_SBI_EXT_NON_BLOCKING_LOAD_STORE,
	AX45MP_SBI_EXT_WRITE_AROUND,
	AX45MP_SBI_EXT_SET_PMA,
	AX45MP_SBI_EXT_FREE_PMA,
	AX45MP_SBI_EXT_PROBE_PMA,
	AX45MP_SBI_EXT_DCACHE_WBINVAL_ALL,
	AX45MP_SBI_EXT_GET_MICM_CTL_STATUS,
	AX45MP_SBI_EXT_GET_MDCM_CTL_STATUS,
	AX45MP_SBI_EXT_GET_MMSC_CTL_STATUS,
	AX45MP_SBI_EXT_GET_MISA_CTL_STATUS,
};

#endif
